"use client"

import { motion, useInView } from "framer-motion"
import { useRef } from "react"
import { ArrowUpRight, Search, Mail, Bot, Monitor, ShoppingBag, Sparkles } from "lucide-react"

const services = [
  { number: "01", title: "SEO που χτίζει αξία", text: "Get found by the right people, then give them a reason to stay. Technical SEO, content, and search strategy built for long-term growth.", icon: Search, className: "md:col-span-2 bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-white border-violet-400/40", iconClass: "bg-violet-400 text-zinc-950" },
  { number: "02", title: "Emails που θέλουν να ανοίξουν", text: "Lifecycle journeys, campaigns, and copy that turns attention into action.", icon: Mail, className: "bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-white", iconClass: "bg-zinc-200 dark:bg-zinc-800 text-[oklch(0.55_0.24_292)] dark:text-[oklch(0.68_0.24_292)]" },
  { number: "03", title: "AI bots με σκοπό", text: "Useful, on-brand AI that answers questions, qualifies leads, and gets work done.", icon: Bot, className: "bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-white", iconClass: "bg-zinc-200 dark:bg-zinc-800 text-[oklch(0.55_0.24_292)] dark:text-[oklch(0.68_0.24_292)]" },
  { number: "04", title: "Websites με δυναμική", text: "Fast, clear digital homes that make your best work impossible to miss.", icon: Monitor, className: "bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-white", iconClass: "bg-zinc-200 dark:bg-zinc-800 text-[oklch(0.55_0.24_292)] dark:text-[oklch(0.68_0.24_292)]" },
  { number: "05", title: "E-shops που πουλάνε", text: "Thoughtful storefronts and smoother journeys from first click to checkout.", icon: ShoppingBag, className: "md:col-span-2 bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-white", iconClass: "bg-zinc-200 dark:bg-zinc-800 text-[oklch(0.55_0.24_292)] dark:text-[oklch(0.68_0.24_292)]" },
]

export function BentoGrid() {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: "-80px" })
  return <section id="services" className="relative px-5 sm:px-8 lg:px-12 py-28"><div className="pointer-events-none absolute inset-x-0 top-0 h-64 tech-grid opacity-20 dark:opacity-40" /><div className="max-w-7xl mx-auto"><motion.div initial={{ opacity: 0, y: 70, scale: 0.94, filter: "blur(12px)" }} animate={isInView ? { opacity: 1, y: 0, scale: 1, filter: "blur(0px)" } : {}} transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }} className="mb-14 grid lg:grid-cols-2 gap-6 items-end"><div><p className="text-sm uppercase tracking-[.2em] text-[oklch(0.55_0.24_292)] dark:text-[oklch(0.68_0.24_292)] mb-5">Τι κάνουμε</p><h2 className="text-5xl sm:text-6xl font-black leading-[.92] tracking-[-.06em] text-zinc-900 dark:text-white max-w-2xl">Μια καλή ιδέα<br /><span className="text-zinc-500">αξίζει μια ολόκληρη ομάδα.</span></h2></div><p className="text-zinc-600 dark:text-zinc-400 leading-7 max-w-md lg:justify-self-end">Χωρίς συνεννόηση με πέντε διαφορετικά agencies. Ενώνουμε στρατηγική, δημιουργικότητα και τεχνολογία, ώστε η επιχείρησή σου να βρίσκεται, να καταλαβαίνεται και να επιλέγεται πιο εύκολα.</p></motion.div><div ref={ref} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{services.map((service, index) => { const Icon = service.icon; return <motion.article key={service.number} initial={{ opacity: 0, y: 55, scale: 0.9, filter: "blur(10px)" }} animate={isInView ? { opacity: 1, y: 0, scale: 1, filter: "blur(0px)" } : {}} transition={{ duration: 0.7, delay: index * .1, ease: [0.16, 1, 0.3, 1] }} className={`group relative min-h-[270px] p-7 rounded-2xl border border-zinc-200 dark:border-zinc-800 overflow-hidden transition-transform hover:-translate-y-1 ${service.className}`}><div className="flex items-start justify-between"><span className="text-sm font-mono opacity-60">{service.number}</span><div className={`rounded-xl p-3 ${service.iconClass}`}><Icon className="h-5 w-5" /></div></div><div className="absolute bottom-7 left-7 right-7"><h3 className="text-2xl font-black tracking-[-.035em] mb-3">{service.title}</h3><p className="text-sm leading-6 opacity-70 max-w-md">{service.text}</p></div><ArrowUpRight className="absolute bottom-7 right-7 h-5 w-5 opacity-0 group-hover:opacity-100 transition-opacity" /></motion.article> })}</div></div></section>
}
