"use client"

import { motion } from "framer-motion"
import { ArrowDownRight, ArrowUpRight } from "lucide-react"
import { Button } from "@/components/ui/button"

export function Hero() {
  return <section className="relative min-h-screen flex items-center px-5 sm:px-8 lg:px-12 pt-32 pb-16 overflow-hidden">
    <div className="absolute inset-0 bg-gradient-to-br from-[oklch(0.055_0.03_276)] via-[oklch(0.09_0.025_276)] to-[oklch(0.14_0.05_292)]" /><div className="absolute inset-0 tech-grid opacity-80" /><div className="absolute inset-0 scanlines opacity-20" />
    <div className="absolute right-[-10%] top-[15%] h-[520px] w-[520px] rounded-full bg-[oklch(0.68_0.24_292)]/15 blur-[120px]" />
    <div className="relative z-10 max-w-7xl mx-auto w-full grid lg:grid-cols-[1.3fr_0.7fr] gap-12 items-end">
      <div>
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6, delay: .15 }} className="mb-7 flex flex-wrap items-center gap-3 text-[10px] font-mono uppercase tracking-[.22em] text-zinc-400"><span className="flex items-center gap-2 rounded-full border border-violet-300/30 bg-violet-300/10 px-3 py-1.5 text-violet-200"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 pulse-glow" />STUDIO_01</span><span>Ανεξάρτητο digital studio</span></motion.div>
        <motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, delay: .25 }} className="max-w-5xl text-[4.35rem] sm:text-7xl lg:text-[8.5rem] leading-[.84] tracking-[-.075em] font-black text-white">Κάνε το<br /><span className="text-[oklch(0.78_0.17_225)]">επόμενο βήμα.</span></motion.h1>
        <div className="mt-7 flex max-w-xl items-center gap-3 text-[10px] font-mono uppercase tracking-[.18em] text-cyan-300/70"><span className="h-px w-8 bg-cyan-300/60" /> strategy / design / technology</div><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6, delay: .45 }} className="mt-5 max-w-xl text-base leading-7 text-zinc-300 sm:text-lg sm:leading-8">Η an email company είναι η ομάδα πίσω από όλα όσα χρειάζεται η επιχείρησή σου για να αναπτυχθεί online — από SEO και email μέχρι AI bots, websites και e-shops.</motion.p>
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6, delay: .55 }} className="mt-10 flex flex-wrap gap-4"><Button asChild size="lg" className="h-13 rounded-full bg-[oklch(0.68_0.24_292)] text-zinc-950 hover:bg-[oklch(0.78_0.17_225)] px-7"><a href="#contact">Πες μας τι ακολουθεί <ArrowUpRight className="ml-2 h-4 w-4" /></a></Button><Button asChild variant="outline" size="lg" className="h-13 rounded-full border-zinc-700 bg-transparent text-zinc-200 hover:bg-zinc-900 px-7"><a href="#services">Δες τις υπηρεσίες <ArrowDownRight className="ml-2 h-4 w-4" /></a></Button></motion.div>
      </div>
      <motion.div initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .8, delay: .45 }} className="mt-12 block pb-2 lg:mt-0 lg:pb-3"><div className="border-t border-zinc-700 pt-5 text-sm text-zinc-500 flex justify-between"><span>Scroll to explore</span><span>01 / 05</span></div><div className="relative mt-8 overflow-hidden rounded-[1.75rem] border border-cyan-300/20 bg-zinc-950/80 shadow-[0_0_50px_oklch(0.78_0.17_225_/_0.12)] backdrop-blur lg:mt-20"><div className="pointer-events-none absolute -right-10 -top-10 h-40 w-40 rounded-full border border-cyan-300/20 shadow-[0_0_50px_oklch(0.78_0.17_225_/_0.18)]" /><div className="pointer-events-none absolute -right-2 -top-2 h-24 w-24 rounded-full border border-violet-300/20" /><div className="flex items-center gap-2 border-b border-zinc-800 px-4 py-3"><span className="h-2 w-2 rounded-full bg-violet-300" /><span className="h-2 w-2 rounded-full bg-cyan-300" /><span className="h-2 w-2 rounded-full bg-zinc-600" /><span className="ml-auto font-mono text-[9px] uppercase tracking-[.18em] text-zinc-600">terminal / hello</span></div><div className="p-5 font-mono text-xs leading-6"><div className="text-zinc-500">$ ./an-email-company</div><div className="text-cyan-300">&gt; hello world<span className="ml-1 inline-block h-4 w-1 animate-pulse bg-violet-300 align-middle" /></div><div className="text-zinc-500">&gt; ideas ready to ship_</div></div></div><div className="mt-10 text-7xl text-[oklch(0.78_0.17_225_/_0.7)] font-medium tracking-tighter drop-shadow-[0_0_24px_oklch(0.78_0.17_225_/_0.25)]">e/</div></motion.div>
    </div>
  </section>
}
